language: python
python:
  - "3.6.2"

before_install:
  - pip install safety
  - safety check -r requirements.txt
  - chmod +x Makefile

install:
  - make init

script:
  - make test

after_success:
  - pip install codecov
  - codecov